[tool.bumpversion]
current_version = "1.0.0"
commit = true
tag = true
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "idf_component.yml"
search = "version: \"{current_version}\""
replace = "version: \"{new_version}\""

[[tool.bumpversion.files]]
filename = "README.md"
search = "brianpugh/esp_tinyuz^{current_version}"
replace = "brianpugh/esp_tinyuz^{new_version}"
