# /// script
# requires-python = ">=3.10"
# dependencies = ["cyclopts>=3", "hdiffpatch==2.4.0"]
# ///
"""Generate the tinyuz test vectors and the example's embedded blob.

Two encoders produce the vectors:

* The upstream ``tinyuz`` CLI, built from the pinned submodule commit, for raw
  tinyuz streams (``hdiffpatch`` has no raw tinyuz compress entry point).
* ``hdiffpatch`` 2.4.0 ``diff_lite(..., compression=TuzConfig(...))`` for the
  tinyuz streams inside HPatchLite diffs, which is exactly what devices receive.
  The expected output is the body of the same diff made with ``compression="none"``.

Every raw stream is round-tripped through ``tinyuz -d`` before it is written.

Build the CLI once (HDiffPatch must be a sibling of the tinyuz checkout)::

    git clone https://github.com/sisong/tinyuz && git -C tinyuz checkout 1d74ffa
    git clone https://github.com/sisong/HDiffPatch && git -C HDiffPatch checkout v5.1.3
    make -C tinyuz MT=0

Then run from the repo root::

    uv run tools/gen_vectors.py --tinyuz /path/to/tinyuz/tinyuz
"""

import random
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

import cyclopts
import hdiffpatch

REPO = Path(__file__).resolve().parent.parent
TEST_VECTORS_C = REPO / "test_apps" / "main" / "test_vectors.c"
EXAMPLE_DATA = REPO / "examples" / "decode_blob" / "main" / "data"

WORDS = (
    "firmware delta update patch device flash partition stream decoder window "
    "dictionary cache literal match length offset byte image boot verify hash "
    "the a of to and in is for on with over radio packet bounded memory"
).split()

app = cyclopts.App(help_on_error=True)


@dataclass
class Vector:
    name: str
    input_index: int
    compressed: bytes
    dict_size: int
    literal_line: bool  # stream may contain literal-line control codes


def make_text(rng: random.Random, n: int) -> bytes:
    out = []
    size = 0
    while size < n:
        line = " ".join(rng.choice(WORDS) for _ in range(rng.randint(4, 14))) + ".\n"
        out.append(line)
        size += len(line)
    return "".join(out).encode()[:n]


def make_firmware(rng: random.Random, n: int) -> bytes:
    """Firmware-like bytes: repeated instruction-ish patterns, tables and noise."""
    patterns = [rng.randbytes(rng.randint(4, 24)) for _ in range(32)]
    out = bytearray()
    while len(out) < n:
        r = rng.random()
        if r < 0.6:
            out += rng.choice(patterns)
        elif r < 0.8:
            out += rng.randbytes(rng.randint(1, 16))
        else:
            out += bytes(rng.randint(1, 32))
    return bytes(out[:n])


def mutate(rng: random.Random, data: bytes) -> bytes:
    out = bytearray(data)
    for _ in range(40):
        pos = rng.randrange(len(out))
        r = rng.random()
        if r < 0.5:
            out[pos : pos + 4] = rng.randbytes(4)
        elif r < 0.75:
            out[pos:pos] = rng.randbytes(rng.randint(1, 64))
        else:
            del out[pos : pos + rng.randint(1, 64)]
    return bytes(out)


def tinyuz_compress(cli: Path, data: bytes, dict_size: int, literal_line: bool) -> bytes:
    with tempfile.TemporaryDirectory() as tmp:
        src, dst, back = Path(tmp, "in"), Path(tmp, "out"), Path(tmp, "back")
        src.write_bytes(data)
        mode = "-c" if literal_line else "-ci"
        subprocess.run([cli, f"{mode}-{dict_size}", src, dst], check=True, capture_output=True)
        subprocess.run([cli, "-d-16", dst, back], check=True, capture_output=True)
        if back.read_bytes() != data:
            raise RuntimeError("tinyuz CLI round trip mismatch")
        return dst.read_bytes()


def lite_body(diff: bytes) -> tuple[int, bytes]:
    """Split an HPatchLite diff into (compress_type, payload after the header)."""
    if diff[:2] != b"hI" or diff[3] >> 6 != 1:
        raise ValueError("not an HPatchLite v1 diff")
    new_size_len = diff[3] & 7
    uncompress_size_len = (diff[3] >> 3) & 7
    return diff[2], diff[4 + new_size_len + uncompress_size_len :]


def c_bytes(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i : i + 16]) + ",")
    return "\n".join(lines) if lines else "    0x00, /* empty */"


def write_c(inputs: list[tuple[str, bytes]], vectors: list[Vector]) -> None:
    parts = [
        "/* Generated by tools/gen_vectors.py; do not edit. */",
        '#include "test_vectors.h"',
        "",
    ]
    for i, (name, data) in enumerate(inputs):
        parts += [f"/* input {i}: {name} */", f"static const uint8_t input_{i}[] = {{", c_bytes(data), "};", ""]
    for i, v in enumerate(vectors):
        parts += [f"static const uint8_t code_{i}[] = {{", c_bytes(v.compressed), "};", ""]
    parts.append("const tuz_test_vector_t tuz_test_vectors[] = {")
    for i, v in enumerate(vectors):
        data = inputs[v.input_index][1]
        parts.append(
            f'    {{"{v.name}", code_{i}, {len(v.compressed)}, input_{v.input_index}, {len(data)}, '
            f"{v.dict_size}, {'true' if v.literal_line else 'false'}}},"
        )
    parts += ["};", "", f"const size_t tuz_test_vector_count = {len(vectors)};", ""]
    TEST_VECTORS_C.write_text("\n".join(parts))


@app.default
def generate(tinyuz: Path, seed: int = 0x7475):
    """Write test_apps/main/test_vectors.c and the example's data files.

    Parameters
    ----------
    tinyuz: Path
        Upstream tinyuz CLI built from commit 1d74ffa (v1.1.1).
    seed: int
        RNG seed for the synthetic inputs.
    """
    rng = random.Random(seed)
    old_fw = make_firmware(rng, 12 * 1024)
    new_fw = mutate(rng, old_fw)
    inputs: list[tuple[str, bytes]] = [
        ("empty", b""),
        ("text 6 KB", make_text(rng, 6 * 1024)),
        ("synthetic firmware 12 KB", old_fw),
        ("random 1 KB", rng.randbytes(1024)),
    ]
    vectors: list[Vector] = []

    for idx, (name, data) in enumerate(inputs):
        for dict_size in (256, 4096):
            for literal_line in (False, True):
                if idx == 0 and dict_size == 4096:
                    continue  # the encoder shrinks the dictionary to the input size anyway
                code = tinyuz_compress(tinyuz, data, dict_size, literal_line)
                tag = "ll" if literal_line else "noll"
                vectors.append(Vector(f"cli/{name}/dict{dict_size}/{tag}", idx, code, dict_size, literal_line))

    none_type, body = lite_body(hdiffpatch.diff_lite(old_fw, new_fw, compression="none"))
    assert none_type == 0
    inputs.append(("HPatchLite body (synthetic firmware diff)", body))
    body_idx = len(inputs) - 1
    for dict_size, literal_line in ((256, False), (4096, False), (4096, True)):
        cfg = hdiffpatch.TuzConfig(dict_size=dict_size, literal_line=literal_line)
        diff = hdiffpatch.diff_lite(old_fw, new_fw, compression=cfg)
        assert hdiffpatch.apply_lite(old_fw, diff) == new_fw
        compress_type, code = lite_body(diff)
        assert compress_type == 1, compress_type  # hpi_compressType_tuz
        tag = "ll" if literal_line else "noll"
        vectors.append(Vector(f"hdiffpatch/diff_lite/dict{dict_size}/{tag}", body_idx, code, dict_size, literal_line))

    write_c(inputs, vectors)
    print(f"wrote {len(vectors)} vectors to {TEST_VECTORS_C.relative_to(REPO)}")

    message = (REPO / "examples" / "decode_blob" / "main" / "data" / "message.txt").read_bytes()
    (EXAMPLE_DATA / "message.txt.tuz").write_bytes(tinyuz_compress(tinyuz, message, 4096, True))
    print("wrote examples/decode_blob/main/data/message.txt.tuz")


if __name__ == "__main__":
    app()
