# /// script
# requires-python = ">=3.10"
# dependencies = ["cyclopts>=3"]
# ///
"""Generate the tinyuz test vectors and the example's embedded blob.

Every stream is made by the upstream ``tinyuz`` CLI built from the pinned
submodule commit (v1.1.1, 1d74ffa; build it as upstream's README describes) and
round-tripped through ``tinyuz -d`` before it is written.

Run from the repo root::

    uv run tools/gen_vectors.py --tinyuz /path/to/tinyuz/tinyuz
"""

import random
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path

import cyclopts

REPO = Path(__file__).resolve().parent.parent
TEST_VECTORS_C = REPO / "test_apps" / "main" / "test_vectors.c"
EXAMPLE_DATA = REPO / "examples" / "decode_blob" / "main" / "data"

WORDS = (
    "compress decode stream window dictionary cache literal match length offset "
    "byte block buffer input output chunk verify checksum small tiny fast "
    "the a of to and in is for on with over radio packet bounded memory"
).split()

app = cyclopts.App(help_on_error=True)


@dataclass
class Vector:
    name: str
    input_index: int
    compressed: bytes
    dict_size: int
    literal_line: bool  # stream may contain literal-line control codes


def make_text(rng: random.Random, n: int) -> bytes:
    out = []
    size = 0
    while size < n:
        line = " ".join(rng.choice(WORDS) for _ in range(rng.randint(4, 14))) + ".\n"
        out.append(line)
        size += len(line)
    return "".join(out).encode()[:n]


def make_structured(rng: random.Random, n: int) -> bytes:
    """Binary with repeated short patterns, zero runs and noise."""
    patterns = [rng.randbytes(rng.randint(4, 24)) for _ in range(32)]
    out = bytearray()
    while len(out) < n:
        r = rng.random()
        if r < 0.6:
            out += rng.choice(patterns)
        elif r < 0.8:
            out += rng.randbytes(rng.randint(1, 16))
        else:
            out += bytes(rng.randint(1, 32))
    return bytes(out[:n])


def make_sparse(rng: random.Random, n: int) -> bytes:
    """Mostly-zero binary with sparse short runs of nonzero bytes."""
    out = bytearray(n)
    for _ in range(n // 256):
        pos = rng.randrange(n)
        run = rng.randbytes(rng.randint(1, 8))
        out[pos : pos + len(run)] = run[: n - pos]
    return bytes(out)


def tinyuz_compress(cli: Path, data: bytes, dict_size: int, literal_line: bool) -> bytes:
    with tempfile.TemporaryDirectory() as tmp:
        src, dst, back = Path(tmp, "in"), Path(tmp, "out"), Path(tmp, "back")
        src.write_bytes(data)
        mode = "-c" if literal_line else "-ci"
        subprocess.run([cli, f"{mode}-{dict_size}", src, dst], check=True, capture_output=True)
        subprocess.run([cli, "-d-16", dst, back], check=True, capture_output=True)
        if back.read_bytes() != data:
            raise RuntimeError("tinyuz CLI round trip mismatch")
        return dst.read_bytes()


def c_bytes(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i : i + 16]) + ",")
    return "\n".join(lines) if lines else "    0x00, /* empty */"


def write_c(inputs: list[tuple[str, bytes]], vectors: list[Vector]) -> None:
    parts = [
        "/* Generated by tools/gen_vectors.py; do not edit. */",
        '#include "test_vectors.h"',
        "",
    ]
    for i, (name, data) in enumerate(inputs):
        parts += [f"/* input {i}: {name} */", f"static const uint8_t input_{i}[] = {{", c_bytes(data), "};", ""]
    for i, v in enumerate(vectors):
        parts += [f"static const uint8_t code_{i}[] = {{", c_bytes(v.compressed), "};", ""]
    parts.append("const tuz_test_vector_t tuz_test_vectors[] = {")
    for i, v in enumerate(vectors):
        data = inputs[v.input_index][1]
        parts.append(
            f'    {{"{v.name}", code_{i}, {len(v.compressed)}, input_{v.input_index}, {len(data)}, '
            f"{v.dict_size}, {'true' if v.literal_line else 'false'}}},"
        )
    parts += ["};", "", f"const size_t tuz_test_vector_count = {len(vectors)};", ""]
    TEST_VECTORS_C.write_text("\n".join(parts))


@app.default
def generate(tinyuz: Path, seed: int = 0x7475):
    """Write test_apps/main/test_vectors.c and the example's data files.

    Parameters
    ----------
    tinyuz: Path
        Upstream tinyuz CLI built from commit 1d74ffa (v1.1.1).
    seed: int
        RNG seed for the synthetic inputs.
    """
    rng = random.Random(seed)
    inputs: list[tuple[str, bytes]] = [
        ("empty", b""),
        ("text 6 KB", make_text(rng, 6 * 1024)),
        ("structured binary 12 KB", make_structured(rng, 12 * 1024)),
        ("random 1 KB", rng.randbytes(1024)),
        ("sparse binary 9 KB", make_sparse(rng, 9 * 1024)),
    ]
    vectors: list[Vector] = []

    for idx, (name, data) in enumerate(inputs):
        for dict_size in (256, 4096):
            for literal_line in (False, True):
                if idx == 0 and dict_size == 4096:
                    continue  # the encoder shrinks the dictionary to the input size anyway
                code = tinyuz_compress(tinyuz, data, dict_size, literal_line)
                tag = "ll" if literal_line else "noll"
                vectors.append(Vector(f"{name}/dict{dict_size}/{tag}", idx, code, dict_size, literal_line))

    write_c(inputs, vectors)
    print(f"wrote {len(vectors)} vectors to {TEST_VECTORS_C.relative_to(REPO)}")

    message = (REPO / "examples" / "decode_blob" / "main" / "data" / "message.txt").read_bytes()
    (EXAMPLE_DATA / "message.txt.tuz").write_bytes(tinyuz_compress(tinyuz, message, 4096, True))
    print("wrote examples/decode_blob/main/data/message.txt.tuz")


if __name__ == "__main__":
    app()
